services:
  postgres:
    image: postgres:15
    container_name: lab_pg
    environment:
      POSTGRES_DB: lab_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"